version: "3"
services:
  api:
    build: .
    command: bash -c "python manage.py run"
    ports:
      - "5000:5000"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
volumes:
  db-data:
