"""empty message

Revision ID: 6b99acba15e4
Revises: 
Create Date: 2019-05-23 00:06:54.486178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b99acba15e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('categoria',
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('nick', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.Column('apellidos', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.Column('quiereEmails', sa.Boolean(), nullable=False),
    sa.Column('valoracion_media', sa.Float(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('radio_ubicacion', sa.Float(), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('Imagen_Perfil_Path', sa.String(length=255), nullable=False),
    sa.Column('borrado', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nick'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('categoria_visitada',
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('categoria_nombre', sa.String(length=30), nullable=False),
    sa.Column('veces', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_nombre'], ['categoria.nombre'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario', 'categoria_nombre')
    )
    op.create_table('conversacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor', sa.String(length=100), nullable=False),
    sa.Column('email_vendedor', sa.String(length=65), nullable=False),
    sa.Column('comprador', sa.String(length=100), nullable=False),
    sa.Column('email_comprador', sa.String(length=65), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comprador'], ['usuario.public_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendedor'], ['usuario.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precioBase', sa.Float(), nullable=False),
    sa.Column('precioAux', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('visualizaciones', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('radio_ubicacion', sa.Float(), nullable=False),
    sa.Column('paypal', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('fechaexpiracion', sa.DateTime(), nullable=True),
    sa.Column('vendedor', sa.Integer(), nullable=False),
    sa.Column('comprador', sa.Integer(), nullable=True),
    sa.Column('borrado', sa.Boolean(), nullable=False),
    sa.Column('tipo', postgresql.ENUM('normal', 'trueque', 'subasta', name='tipoProducto'), nullable=False),
    sa.ForeignKeyConstraint(['comprador'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['vendedor'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reporte_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipoReporte', sa.String(length=255), nullable=False),
    sa.Column('reportado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reportado'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id', 'reportado')
    )
    op.create_table('seguir',
    sa.Column('seguidor', sa.Integer(), nullable=False),
    sa.Column('seguido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seguido'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['seguidor'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('seguidor', 'seguido')
    )
    op.create_table('valoracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('puntuador', sa.Integer(), nullable=False),
    sa.Column('puntuado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['puntuado'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['puntuador'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id', 'puntuador', 'puntuado')
    )
    op.create_table('deseados',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'producto_id')
    )
    op.create_table('mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('conversacion', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['conversacion'], ['conversacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multimedia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Boolean(), nullable=False),
    sa.Column('producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pertenece',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_nombre', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['categoria_nombre'], ['categoria.nombre'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('producto_id', 'categoria_nombre')
    )
    op.create_table('puja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('producto', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id', 'usuario', 'producto')
    )
    op.create_table('reporte_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipoReporte', sa.String(length=255), nullable=False),
    sa.Column('reportado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reportado'], ['producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'reportado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reporte_producto')
    op.drop_table('puja')
    op.drop_table('pertenece')
    op.drop_table('multimedia')
    op.drop_table('mensaje')
    op.drop_table('deseados')
    op.drop_table('valoracion')
    op.drop_table('seguir')
    op.drop_table('reporte_usuario')
    op.drop_table('producto')
    op.drop_table('conversacion')
    op.drop_table('categoria_visitada')
    op.drop_table('usuario')
    op.drop_table('categoria')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
