"""empty message

Revision ID: aee6a91ef40a
Revises: 6b99acba15e4
Create Date: 2019-05-25 18:59:08.553679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee6a91ef40a'
down_revision = '6b99acba15e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'token')
    # ### end Alembic commands ###
