"""empty message

Revision ID: f14b5273cf4c
Revises: 
Create Date: 2019-04-06 16:03:22.142937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14b5273cf4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categoria',
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('nick', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.Column('apellidos', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.Column('quiereEmails', sa.Boolean(), nullable=False),
    sa.Column('valoracionMedia', sa.Float(), nullable=True),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('Imagen_Perfil_Path', sa.String(length=255), nullable=False),
    sa.Column('borrado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nick'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('Mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('emisor', sa.Integer(), nullable=False),
    sa.Column('receptor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emisor'], ['Usuario.id'], ),
    sa.ForeignKeyConstraint(['receptor'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id', 'emisor', 'receptor')
    )
    op.create_table('Producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precioBase', sa.Float(), nullable=False),
    sa.Column('precioAux', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('visualizaciones', sa.Integer(), nullable=False),
    sa.Column('paypal', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('vendedor', sa.Integer(), nullable=False),
    sa.Column('comprador', sa.Integer(), nullable=True),
    sa.Column('borrado', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comprador'], ['Usuario.id'], ),
    sa.ForeignKeyConstraint(['vendedor'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ReporteUsuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipoReporte', sa.String(length=255), nullable=False),
    sa.Column('reportado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reportado'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id', 'reportado')
    )
    op.create_table('Seguir',
    sa.Column('seguidor', sa.Integer(), nullable=False),
    sa.Column('seguido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seguido'], ['Usuario.id'], ),
    sa.ForeignKeyConstraint(['seguidor'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('seguidor', 'seguido')
    )
    op.create_table('Valoracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('puntuador', sa.Integer(), nullable=False),
    sa.Column('puntuado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['puntuado'], ['Usuario.id'], ),
    sa.ForeignKeyConstraint(['puntuador'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id', 'puntuador', 'puntuado')
    )
    op.create_table('Deseados',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['Producto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'producto_id')
    )
    op.create_table('Pertenece',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_nombre', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['categoria_nombre'], ['Categoria.nombre'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['Producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('producto_id', 'categoria_nombre')
    )
    op.create_table('ReporteProducto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipoReporte', sa.String(length=255), nullable=False),
    sa.Column('reportado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reportado'], ['Producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'reportado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReporteProducto')
    op.drop_table('Pertenece')
    op.drop_table('Deseados')
    op.drop_table('Valoracion')
    op.drop_table('Seguir')
    op.drop_table('ReporteUsuario')
    op.drop_table('Producto')
    op.drop_table('Mensaje')
    op.drop_table('blacklist_tokens')
    op.drop_table('Usuario')
    op.drop_table('Categoria')
    # ### end Alembic commands ###
